export const executives = [
    {
      title: "Bobby F.",
      role: "President",
      description: "Hey! My name is Bobby, and I serve as the founder and current director of FutureMD. As an IB student, I am very passionate about biology and chemistry, which aligns perfectly with my goal to become a dermatologist! In my spare time, I love playing basketball and volleyball at high levels, and I enjoy coaching & refereeing basketball at my local club.",
      image: "team/bobby.jpg",
      linkedin: "https://www.linkedin.com/in/bobbyf0814/",
      instagram: "https://www.instagram.com/bobbyf0814",
    },
    {
        title: "Nirupa W.",
        role: "President",
        description: "Hey there! I’m Nirupa, a Founder and President of the organization. I'm extremely passionate about FutureMD because of my persisting interest in Medicine. This organization not only fuels my enthusiasm for the industry but also serves as a learning opportunity for me to deepen my understanding of medicine! Outside of my professional interests, I enjoy playing volleyball, basketball, and soccer.",
        image: "team/nirupa.jpg",
        linkedin: "https://www.linkedin.com/in/nirupa-wimalawickrama-096734254/",
        instagram: "https://www.instagram.com/nirupa.w08",
    },
    {
      title: "Salma M.",
      role: "Vice-President",
      description: "Hi! I’m Salma, a vice president of FutureMD. My favourite subjects are math and science, and I enjoy designing in my free time. I also love to paint and play with my two adorable cats!",
      image: "team/salma.jpg",
      instagram: "https://www.instagram.com/sxlmx_m",
    },
    {
      title: "Advay C.",
      role: "Lead-Developer",
      description: "Hey, I'm Advay, and I'm the lead developer at FutureMD. I'm a passionate developer and IB student who loves to build things and solve problems. I'm always looking for new challenges and opportunities to learn and grow. In my free time, I enjoy playing badminton, basketball and building robots!",
      image: "team/advay.jpg",
      linkedin: "https://www.linkedin.com/in/advay",
      instagram: "https://www.instagram.com/advay.chandorkar_/",
    },
    {
      title: "Joanne L.",
      role: "Head of Design",
      description: "Hello! I'm Joanne, an IB student interested in all things STEM! Within FutureMD, I'm apart of the design and marketing/outreach subteams. In my free time, you can catch me designing graphics, dancing or volunteering for organizations like this!",
      image: "logo.png",
      instagram: "https://www.instagram.com/jnne_lu",
    },
]