export const team = [
    {
      title: "Bobby F.",
      role: "President",
      description: "Hey! My name is Bobby, and I serve as the founder and current director of FutureMD. As an IB student, I am very passionate about biology and chemistry, which aligns perfectly with my goal to become a dermatologist! In my spare time, I love playing basketball and volleyball at high levels, and I enjoy coaching & refereeing basketball at my local club..",
      image: "logo.png",
      linkedin: "https://www.linkedin.com/in/bobbyf0814/",
      instagram: "https://www.instagram.com/bobbyf0814",
    },
    {
        title: "Nirupa W.",
        role: "President",
        description: "John has extensive experience in product management, focusing on developing innovative solutions that meet user needs and business goals.",
        image: "logo.png",
        linkedin: "https://www.linkedin.com/in/nirupa-wimalawickrama-096734254/",
        instagram: "https://www.instagram.com/nirupa.w08",
    },
    {
      title: "Yang X.",
      role: "Vice-President",
      description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder.",
      image: "logo.png",
      linkedin: "https://www.linkedin.com/in/yangxuejfss/",
      instagram: "https://www.instagram.com/thatonekidcalledyang",
    },
    {
      title: "Salma M.",
      role: "Vice-President",
      description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder.",
      image: "logo.png",
      linkedin: "https://www.linkedin.com/in/advay",
      instagram: "https://www.instagram.com/sxlmx_m",
    },
    {
      title: "Advay C.",
      role: "Lead-Developer",
      description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder.",
      image: "logo.png",
      linkedin: "https://www.linkedin.com/in/advay",
      instagram: "https://www.instagram.com/advay.chandorkar_/",
    },
    {
      title: "Joanne L.",
      role: "Head of Design",
      description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder.",
      image: "logo.png",
      linkedin: "https://www.linkedin.com/in/advay",
      instagram: "https://www.instagram.com/jnne_lu",
    },
    {
      title: "Akalya G.",
      role: "Outreach",
      description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder.",
      image: "logo.png",
      linkedin: "https://www.linkedin.com/in/akalya-g-19763a257/",
      instagram: "https://www.instagram.com/akalyagunen_",
    },
    {
      title: "Waleed A.",
      role: "Marketing",
      description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder.",
      image: "logo.png",
      linkedin: "https://www.linkedin.com/in/waleed-a-614363299/",
      instagram: "https://www.instagram.com/ohwaleeed",
    },
    {
      title: "Mujtaba A.",
      role: "Design",
      description: "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content. Lorem ipsum may be used as a placeholder.",
      image: "logo.png",
      linkedin: "https://www.linkedin.com/in/advay",
      instagram: "https://www.instagram.com/_mujtabaawan",
    },

];
  
