export const team = [
    {
      title: "Bobby F.",
      role: "President",
      description: "Hey! My name is Bobby, and I serve as the founder and current director of FutureMD. As an IB student, I am very passionate about biology and chemistry, which aligns perfectly with my goal to become a dermatologist! In my spare time, I love playing basketball and volleyball at high levels, and I enjoy coaching & refereeing basketball at my local club.",
      image: "team/bobby.jpg",
      linkedin: "https://www.linkedin.com/in/bobbyf0814/",
      instagram: "https://www.instagram.com/bobbyf0814",
      email: "fangbobby146@gmail.com",
    },
    {
      title: "Nirupa W.",
      role: "President",
      description: "Hey there! I’m Nirupa, a Founder and President of the organization. I'm extremely passionate about FutureMD because of my persisting interest in Medicine. This organization not only fuels my enthusiasm for the industry but also serves as a learning opportunity for me to deepen my understanding of medicine! Outside of my professional interests, I enjoy playing volleyball, basketball, and soccer.",
      image: "team/nirupa.jpg",
      linkedin: "https://www.linkedin.com/in/nirupa-wimalawickrama-096734254/",
      instagram: "https://www.instagram.com/nirupa.w08",
      email: "nw2008sci@gmail.com",
    },
    {
      title: "Salma M.",
      role: "Vice-President",
      description: "Hi! I’m Salma, a vice president of FutureMD. My favourite subjects are math and science, and I enjoy designing in my free time. I also love to paint and play with my two adorable cats!",
      image: "team/salma.jpg",
      instagram: "https://www.instagram.com/sxlmx_m",
      email: "salmakahlawy40@gmail.com",
    },
    {
      title: "Advay C.",
      role: "Lead-Developer",
      description: "Hey, I'm Advay, and I'm the lead developer at FutureMD. I'm a passionate developer and IB student who loves to build things and solve problems. I'm always looking for new challenges and opportunities to learn and grow. In my free time, I enjoy playing badminton, basketball and building robots!",
      image: "team/advay.jpg",
      linkedin: "https://www.linkedin.com/in/advay",
      instagram: "https://www.instagram.com/advay.chandorkar_/",
      email: "advay.chandorkar@gmail.com",
    },
    {
      title: "Joanne L.",
      role: "Head of Design",
      description: "Hello! I'm Joanne, an IB student interested in all things STEM! Within FutureMD, I'm apart of the design and marketing/outreach subteams. In my free time, you can catch me designing graphics, dancing or volunteering for organizations like this!",
      image: "team/joanne.jpg",
      instagram: "https://www.instagram.com/jnne_lu",
      email: "joannelu0830@gmail.com",
    },
    {
      title: "Arghya V.",
      role: "Design & Developer",
      description: "Hello! My name is Arghya, and I am a passionate designer as part of FutureMD. As a kid, I have always had a sincere passion about organic chemistry, and I wish to pursue my learning in the International Baccalaureate (IB) program. I aspire to be a biomedical engineer someday. In my spare time, I enjoy playing basketball, play video games, and learn!",
      image: "team/arghya.jpg",
      linkedin: "https://www.linkedin.com/in/arghya-vyas-2a40a72b1/",
      instagram: "https://www.instagram.com/arghyavarfet/",
      email: "arghyavyas775@gmail.com",
    },
    {
      title: "Akalya G.",
      role: "Outreach",
      description: "Hi! My name is Akalya, and I am part of the Outreach team in FutureMD. In the future, I would like to pursue a career as a pediatrician or bioengineer, as I am passionate about mathematics, biology, and chemistry. I am currently studying in the IB program, and I'm excited to help this team out. 🙂",
      image: "team/akalya.jpg",
      linkedin: "https://www.linkedin.com/in/akalya-g-19763a257/",
      instagram: "https://www.instagram.com/akalyagunen_",
      email: "akalyagunen@gmail.com",
    },
    {
      title: "Sohun J.",
      role: "Outreach",
      description: "I’m an IB student and the Outreach Lead at FutureMD, where I work to connect youth with opportunities to explore careers in medicine. I have experience in healthcare, leadership, and community service through roles with the City of Mississauga, DECA, and SHAD Canada. I’m passionate about making medical education more accessible and helping students feel confident about their future in healthcare.",
      image: "team/sohun.jpg",
      linkedin: "https://www.linkedin.com/in/sohun-jhaveri-46448331a/",
      instagram: "https://www.instagram.com/08_sohun/",
      email: "sohun8j@gmail.com",
    },
    {
      title: "Kashmir P.",
      role: "Marketing",
      description: "Hello! My name is Kashmir, and my job at FutureMD is to help market the organization. I am currently attending Glenforest Secondary School where I am part of the International Baccalaureate (IB) program. I am passionate about mathematics and biology, which has led me to want to become a Medical Doctor. In my spare time, I like to play Hockey, Baseball, Chess and Video Games. I also enjoy reading and learning about the world around us.",
      image: "logo.png",
      linkedin: "https://www.linkedin.com/in/kashmir-parmar-9a346331a/",
      instagram: "https://www.instagram.com/futuremd_team",
      email: "ksp3141@gmail.com",
    },
    {
      title: "Kishan S.",
      role: "Logistics",
      description: "Hi, I am Kishan S. I am a passion driven STEM enthusiast with a strong background in robotics. Experienced in designing, building, and wiring robotic systems, with a keen interest in automation and AI. I like to lead in collaborate innovative projects, leveraging skills in mechanical engineering, electronics, and computer science.",
      image: "team/kishan.jpg",
      linkedin: "https://www.linkedin.com/in/kishan-s-998898329//",
      instagram: "https://www.instagram.com/k1shxnsuhi/",
      email: "kishansuhirthan@gmail.com",
    },
];
